"""
services/export_service.py — FR-13: CSV + signed Markdown
"""

import json
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select
from models.attestation import AttestationEntry
from services.crypto_service import load_public_key, verify_signature

async def export_signed_report(db: AsyncSession, shutdown_event_id: str) -> str:
    """Generates a standalone Markdown file with attestation proof."""
    result = await db.execute(select(AttestationEntry).where(AttestationEntry.shutdown_event_id == shutdown_event_id))
    entry = result.scalar_one_or_none()
    
    if not entry:
        return "No attestation entry found for this shutdown event."
        
    try:
        public_key = load_public_key()
        is_valid = verify_signature(entry.payload_json, bytes.fromhex(entry.signature), public_key)
        verification_status = "✅ Verified" if is_valid else "❌ Verification Failed"
    except Exception as e:
        verification_status = f"❌ Verification Error: {e}"
        
    payload_dict = json.loads(entry.payload_json)
        
    report = f"""# Kill-Switch Attestation Report
    
**Event ID:** `{shutdown_event_id}`
**Timestamp:** `{payload_dict.get("timestamp")}`

## 1. Test Result Data
- **Revocation Latency:** `{payload_dict.get("revocation_latency_ms"):.2f} ms`
- **Leaked Channels:** `{len(payload_dict.get("leaked_channels", []))}`
- **In-flight Failures:** `{payload_dict.get("in_flight_failures")}`

## 2. Cryptographic Proof
**Signature (Ed25519, Hex):**
```
{entry.signature}
```

**Payload Hash:**
```
{entry.entry_hash}
```
**Previous Block Hash:**
```
{entry.prev_hash}
```

## 3. Verification Status
**{verification_status}** (checked against known public key at export time)

---
*Generated by Kill-Switch Attestation System*
"""
    return report

async def get_experiment_csv(db: AsyncSession, experiment_id: str) -> str:
    """Generates CSV content for an experiment."""
    from models.experiment import ExperimentResult
    
    result = await db.execute(select(ExperimentResult).where(ExperimentResult.experiment_id == experiment_id).order_by(ExperimentResult.cycle_number))
    results = result.scalars().all()
    
    csv_lines = ["cycle_number,latency_ms,leak_count,in_flight_failures,retry_count,success_rate,shutdown_event_id"]
    for r in results:
        csv_lines.append(f"{r.cycle_number},{r.latency_ms:.2f},{r.leak_count},{r.in_flight_failures},{r.retry_count},{r.success_rate:.2f},{r.shutdown_event_id}")
        
    return "\n".join(csv_lines)
